code changes

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -107,7 +107,7 @@ snyk-code-analysis:
         snyk config set https://app.snyk.io/org/ps-data-services
         echo "--> Iniciating SNYK Code Analysis"
         snyk test --json-file-output="test.json" --all-projects --debug || echo "snyk test completed with errors"
-        snyk test ${CI_PROJECT_DIR} --project-id="${SNYK_PROJECT_ID}" --json --all-projects --json-file-output="snyk-code-analysis.json" --debug || echo "snyk test completed with errors"
+        snyk code test --project-id="${SNYK_PROJECT_ID}" --json --all-projects --json-file-output="snyk-code-analysis.json" --debug || echo "snyk test completed with errors"
         echo "--> Code Check Completed"
       fi
   artifacts:
